### ISSUE TITLE
U232 example fails

### ISSUE THREAD

**Issue by wryssens** [pyneb/pyneb#26]
At the time of writing, the U232 fails with the following message:

```
Traceback (most recent call last):
  File "/home/wryssens/Documents/Codes/pyneb/examples/232U/main.py", line 50, in <module>
    allowedEndpoints, allowedIndices = \
ValueError: too many values to unpack (expected 2)

```
which is due to the fact that the function-call on line 50

`allowedEndpoints, allowedIndices = \
    pyneb.SurfaceUtils.find_endpoints_on_grid(coordMeshTuple,zz)`

no longer returns **two** outputs by default. 

Changing the call to 
```
pyneb.SurfaceUtils.find_endpoints_on_grid(coordMeshTuple,zz,returnIndices=True)
```

solves this issue.

**Comment by dlay97** [comment]
The example in the repo has been fixed, using exactly your suggestion.
